### ISSUE TITLE
Unable to map inner properties of Photos/Videos/Collections/CollectionMedia objects

### ISSUE THREAD

**Issue by nastasyaaaa** [devscast/pexels#3]
**Describe the bug**
\Devscast\Pexels\Client::getMappedData() always throws exception with `incorrect type` message.

**To Reproduce**
1. Initiate `\Devscast\Pexels\Client` with auth token.
2. Call `$client->searchPhotos('westie dog')`
3. Exception is trowed with following error message: `Unexpected $type value`

**Additional Info**
Denormalizer returns the instance of one of this classes `Photos|Videos|Collections|CollectionMedia`. But then, to map inner properties (e.g. photos/videos/collections/media), the check via `is_subclass_of` is used, which always returns false.

Would be great if you take a look. Thanks a lot!

**Comment by bernard-ng** [comment]
@nastasyaaaa I'm on it
